"""update document schema

Revision ID: 05e3b2c00b9c
Revises: 75a911ca2f3c
Create Date: 2026-08-13 12:18:32.222795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e3b2c00b9c'
down_revision: Union[str, Sequence[str], None] = '75a911ca2f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('is_processed', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('uploaded_by', sa.UUID(), nullable=False))
    op.alter_column('documents', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'])
    op.drop_column('documents', 'user_id')
    op.drop_column('documents', 'file_type')
    op.drop_column('documents', 'file_name')
    op.drop_column('documents', 'embedding_status')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('embedding_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'is_processed')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'filename')
    # ### end Alembic commands ###
